version = 0

[transient_prompt]
  template = ' ❯ '
  foreground = '#994de6'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

#[[blocks.segments]]
# template = '╭─[<cyan>{{ .UserName }}</><red>@</><blue>{{ .HostName }}</>]  '
#type = 'session'
#style = 'plain'

  [[blocks.segments]]
    type = 'path'
    template = '<#ffffff>╭─[</>{{ .Path }}<#ffffff>]</>'
    foreground = '#ff5555'

    [blocks.segments.options]
      style = "agnoster_full"
      max_width = 2
      home_icon = "󰚡 "
      hide_root_location = 'true'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}<#ffffff>)</>'
    foreground = '#3C873A'
    type = 'node'
    style = 'plain'

    [blocks.segments.options]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a></> '
      yarn_icon = ' <#348cba></>'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#FFE873'
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#ec2729'
    type = 'java'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#0d6da8'
    type = 'dotnet'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#06aad5'
    type = 'go'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#925837'
    type = 'rust'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#055b9c'
    type = 'dart'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#ce092f'
    type = 'angular'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#de1f84'
    type = 'aurelia'
    style = 'plain'

  [[blocks.segments]]
    template = '<#1e293b>(</>{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}<#1e293b>)</>'
    foreground = '#ffffff'
    type = 'nx'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#359a25'
    type = 'julia'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#9c1006'
    type = 'ruby'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#5398c2'
    type = 'azfunc'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{.Profile}}{{if .Region}}@{{.Region}}{{end}}<#ffffff>)</>'
    foreground = '#faa029'
    type = 'aws'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}<#ffffff>)</>'
    foreground = '#316ce4'
    type = 'kubectl'
    style = 'plain'


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰──'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>[</>{{ .HEAD }}{{ if .Staging.Changed }}<#00AA00> ● {{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }}<#D75F00> ● {{ .Working.String }}</>{{ end }}<#ffffff>]-</>'
    foreground = '#e0f8ff'
    type = 'git'
    style = 'plain'

    [blocks.segments.options]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '❯ '
    foreground = '#00ff00'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']

    [blocks.segments.options]
      always_enabled = true
