color0 #040404
color1 #db6088
color2 #9cda7c
color3 #9dafd1
color4 #b968fc
color5 #875faf
color6 #80e6cc
color7 #ccd2d9
color8 #a1a0ad
color9 #db6088
color10 #87ff5f
color11 #6666e6
color12 #ce67f0
color13 #ab92fc
color14 #1ae6cc
color15 #e1d6f8

cursor                #e1d6f8
cursor_text_color     #201430
background            #040404
foreground            #e1d6f8
selection_foreground  #201430
selection_background  #8edf5f
active_border_color   #b968fc
inactive_border_color #39274c
url_color             #b968fc

active_tab_foreground   #201430
active_tab_background   #b968fc
inactive_tab_foreground #a1a0ad
inactive_tab_background #39274c
cursor_trail_color      #a1a0ad
