cursor #efecf4
cursor_text_color #95abdf

foreground            #efecf4
background            #19171c
selection_foreground  #0c0a0f
selection_background  #398bc6
url_color             #56a8e5

color0   #26232a
color1   #ff4f85
color2   #56e567
color3   #fff54f
color4   #3694d9
color5   #003c6a
color6   #56a8e5
color7   #dee8f0
color8   #868e94
color9   #ff87ac
color10  #8fff9d
color11  #fff88f
color12  #76c2fb
color13  #8fcfff
color14  #b7e0ff
color15  #f7fbff
