
lines 25

columns 10

edge top

layer top

background_opacity 0.65

hide_on_focus_loss no


margin_left 25

margin_right 900

margin_top 0

margin_bottom 0

class kittyquick

start_as_hidden no

grab_keyboard no

focus_policy on-demand

kitty_override hide_window_decorations no
